# Generated by Django 5.1.4 on 2025-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROUTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORIGIN', models.TextField(max_length=100)),
                ('DESTINATION', models.TextField(max_length=100)),
                ('TIME', models.PositiveIntegerField()),
            ],
        ),
    ]
