# Generated by Django 5.1.4 on 2025-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_time_routes_travel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='DESTINATION',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='ORIGIN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routes',
            name='TRAVEL_TIME',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='routes',
            table='ROUTES',
        ),
    ]
